/* Generated By:JavaCC: Do not edit this line. adderConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface adderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDREACH = 1;
  /** RegularExpression Id. */
  int CLASSTYPE = 2;
  /** RegularExpression Id. */
  int VOID = 3;
  /** RegularExpression Id. */
  int NUMTYPES = 4;
  /** RegularExpression Id. */
  int FLOATTYPE = 5;
  /** RegularExpression Id. */
  int STRINGTYPE = 6;
  /** RegularExpression Id. */
  int CHARTYPE = 7;
  /** RegularExpression Id. */
  int BOOL = 8;
  /** RegularExpression Id. */
  int LPAR = 9;
  /** RegularExpression Id. */
  int RPAR = 10;
  /** RegularExpression Id. */
  int LBRACE = 11;
  /** RegularExpression Id. */
  int RBRACE = 12;
  /** RegularExpression Id. */
  int SEMICOLON = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int COMA = 15;
  /** RegularExpression Id. */
  int LOOPFOR = 16;
  /** RegularExpression Id. */
  int LOOPDO = 17;
  /** RegularExpression Id. */
  int LOOPWHILE = 18;
  /** RegularExpression Id. */
  int ARITM = 19;
  /** RegularExpression Id. */
  int ASIGN = 20;
  /** RegularExpression Id. */
  int CONDITION = 21;
  /** RegularExpression Id. */
  int RELAT = 22;
  /** RegularExpression Id. */
  int LOGIC = 23;
  /** RegularExpression Id. */
  int STRUCTTYPE = 24;
  /** RegularExpression Id. */
  int CLASS = 25;
  /** RegularExpression Id. */
  int ALT = 26;
  /** RegularExpression Id. */
  int FOREACH = 27;
  /** RegularExpression Id. */
  int CATCH = 28;
  /** RegularExpression Id. */
  int TRYBLOCK = 29;
  /** RegularExpression Id. */
  int PRINTOUT = 30;
  /** RegularExpression Id. */
  int IFSTRUCT = 31;
  /** RegularExpression Id. */
  int SWITCHSTRUCT = 32;
  /** RegularExpression Id. */
  int THEN = 33;
  /** RegularExpression Id. */
  int PACKEXP = 34;
  /** RegularExpression Id. */
  int IMPORT = 35;
  /** RegularExpression Id. */
  int HCLASS = 36;
  /** RegularExpression Id. */
  int DEF = 37;
  /** RegularExpression Id. */
  int CONST = 38;
  /** RegularExpression Id. */
  int RETURN = 39;
  /** RegularExpression Id. */
  int ENUM = 40;
  /** RegularExpression Id. */
  int LIST = 41;
  /** RegularExpression Id. */
  int STACK = 42;
  /** RegularExpression Id. */
  int QUEUE = 43;
  /** RegularExpression Id. */
  int ARRAY = 44;
  /** RegularExpression Id. */
  int STRUCT = 45;
  /** RegularExpression Id. */
  int IDENTIFIER = 46;
  /** RegularExpression Id. */
  int NUMBER = 47;
  /** RegularExpression Id. */
  int LETTER = 48;
  /** RegularExpression Id. */
  int UNDERSC = 49;
  /** RegularExpression Id. */
  int WORD = 50;
  /** RegularExpression Id. */
  int STRING = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IDREACH>",
    "\"abstract | static | const | implements | clascy \"",
    "\"void \"",
    "<NUMTYPES>",
    "<FLOATTYPE>",
    "\"string\"",
    "\"char\"",
    "\"bool\"",
    "\"( \"",
    "\") \"",
    "\"{ \"",
    "\"} \"",
    "\"; \"",
    "\":\"",
    "\", \"",
    "\"for \"",
    "\"do \"",
    "\"while \"",
    "\"+| -| *| /\"",
    "\"= \"",
    "\"true | false\"",
    "<RELAT>",
    "<LOGIC>",
    "<STRUCTTYPE>",
    "\"class \"",
    "<ALT>",
    "<FOREACH>",
    "<CATCH>",
    "\"try \"",
    "\"print | println | writeline\"",
    "\"if \"",
    "\"switch | stoom \"",
    "\"then \"",
    "\"packexp \"",
    "\"import \"",
    "\">> \"",
    "\"def\"",
    "\"const \"",
    "\"return \"",
    "\"enum \"",
    "\"list \"",
    "\"stack \"",
    "\"queue \"",
    "\"array \"",
    "\"struct \"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<LETTER>",
    "\"_\"",
    "<WORD>",
    "<STRING>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
